[project]
name = "ai-genai-rag-asistente-normativa-sincro"
version = "0.1.0"
description = "Asistente virtual de normativa"
authors = [{ name = "Laren Osorio Toribio", email = "losorio@rcp.pe" }]
requires-python = ">=3.12"

dependencies = [
  "pymupdf",
  "unstructured",
  "sentence-transformers",
  "qdrant-client",
  "langchain",
  "langchain-experimental",
  "transformers",
  "accelerate",
  "ollama",
  "streamlit",
  "python-dotenv",
  "tqdm",
  "scikit-learn",
  "pandas",
  "huggingface_hub",
  "gradio",
  "tiktoken",
  "chainlit<2.6.0",
  "langchain-ollama",
  "langchain-community",
  "mistralai",
  "openpyxl",
  "pypdf2",
  "ragas",
  "asyncpg",
  "boto3",
  "translate",
  "psutil",
  "requests",
  "python-docx>=1.2.0",
  "langdetect>=1.0.9",
  "docx2txt>=0.9",
  "docx2pdf>=0.1.8",
  "reportlab>=4.0.0",
  "pydantic>=2.0.0",
  "pydantic-settings>=2.0.0",
]

[tool.uv]
managed = true
